git clone https://github.com/mileszs/ack.vim.git bundle/ack
git clone https://github.com/kien/ctrlp.vim bundle/ctrlp.vim
git clone https://github.com/sjl/gundo.vim.git bundle/gundo
git clone https://github.com/scrooloose/nerdtree bundle/nerdtree
git clone https://github.com/vim-scripts/pep8.git bundle/pep8
git clone https://github.com/fs111/pydoc.vim.git bundle/pydoc
git clone https://github.com/mitechie/pyflakes-pathogen.git bundle/pyflakes-pathogen.git
git clone https://github.com/msanders/snipmate.vim.git bundle/snipmate
git clone https://github.com/ervandew/supertab.git bundle/supertab
git clone https://github.com/altercation/vim-colors-solarized bundle/vim-colors-solarized
git clone https://github.com/tpope/vim-markdown bundle/vim-markdown
git clone https://github.com/tpope/vim-surround.git bundle/surround
git clone https://github.com/vim-scripts/closetag.vim.git bundle/closetag.vim
git clone https://github.com/elzr/vim-json bundle/vim-json
