git clone https://github.com/mileszs/ack.vim bundle/ack
git clone https://github.com/kien/ctrlp.vim bundle/ctrlp
git clone https://github.com/sjl/gundo.vim bundle/gundo
git clone https://github.com/scrooloose/nerdtree bundle/nerdtree
git clone https://github.com/vim-scripts/pep8 bundle/pep8
git clone https://github.com/fs111/pydoc.vim bundle/pydoc
git clone https://github.com/mitechie/pyflakes-pathogen bundle/pyflakes-pathogen
git clone https://github.com/msanders/snipmate.vim bundle/snipmate
git clone https://github.com/ervandew/supertab bundle/supertab
git clone https://github.com/altercation/vim-colors-solarized bundle/vim-colors-solarized
git clone https://github.com/tpope/vim-markdown bundle/vim-markdown
git clone https://github.com/tpope/vim-surround bundle/surround
git clone https://github.com/vim-scripts/closetag.vim bundle/closetag
git clone https://github.com/elzr/vim-json bundle/vim-json
git clone https://github.com/vim-scripts/DeleteTrailingWhitespace bundle/DeleteTrailingWhitespace 
